# MySQL.  Versions 4.1 and 5.0 are recommended.
# 
# Install the MYSQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem 'mysql2'
#
# And be sure to use new-style password hashing:
# development:
#   adapter: postgresql
#   encoding: utf8
#   reconnect: false
#   database: vishnu_app3
#   port: 5432
#   host: localhost
#   pool: 5
#   username: postgres
#   password: postgres
# development:
#   adapter: postgresql
#   encoding: utf8
#   reconnect: false
#   database: h1bwiki
#   port: 5432
#   host: h1bwiki.celqzzcdkk3r.us-west-2.rds.amazonaws.com
#   pool: 5
#   username: h1bwiki
#   password: h1bwikiapp
# development:
#   adapter: postgresql
#   encoding: utf8
#   reconnect: false
#   database: vishnu_app3
#   port: 5432
#   host: localhost
#   pool: 5
#   username: h1bwiki
#   password: h1bwikiapp

#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
development:
 adapter: mysql2
 encoding: utf8
 reconnect: false
 database: sample_app_jquery
 pool: 5
 username: root
 password: root
 socket: /var/run/mysqld/mysqld.sock

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
#test:
#  adapter: mysql2
#  encoding: utf8
#  reconnect: false
#  database: vishnu_app
#  pool: 5
#  username: root
#  password: root
#  socket: /var/run/mysqld/mysqld.sock
#
#production:
#  adapter: mysql2
#  encoding: utf8
#  reconnect: false
#  database: vishnu_app
#  pool: 5
#  username: root
#  password: root
#  socket: /var/run/mysqld/mysqld.sock
